src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Enum\CommentStatusEnum;
use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column]
	private ?int $id = null;

	#[ORM\Column(type: Types::TEXT)]
	private ?string $content = null;

	#[ORM\Column(enumType: CommentStatusEnum::class)]
	private ?CommentStatusEnum $status = null;

	#[ORM\ManyToOne(inversedBy: 'comments')]
	#[ORM\JoinColumn(nullable: false)]
	private ?User $author = null;

	#[ORM\ManyToOne(inversedBy: 'comments')]
	#[ORM\JoinColumn(nullable: false)]
	private ?Media $media = null;

	#[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'comments')]
	private ?self $parentComment = null;

	/**
	 * @var Collection<int, self>
	 */
	#[ORM\OneToMany(targetEntity: self::class, mappedBy: 'parentComment', cascade: ['remove'])]
	#[ORM\JoinColumn(onDelete: 'CASCADE')]
	private Collection $comments;

	public function __construct()
	{
		$this->comments = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	public function getContent(): ?string
	{
		return $this->content;
	}

	public function setContent(string $content): static
	{
		$this->content = $content;

		return $this;
	}

	public function getStatus(): ?CommentStatusEnum
	{
		return $this->status;
	}

	public function setStatus(CommentStatusEnum $status): static
	{
		$this->status = $status;

		return $this;
	}

	public function getAuthor(): ?User
	{
		return $this->author;
	}

	public function setAuthor(?User $author): static
	{
		$this->author = $author;

		return $this;
	}

	public function getMedia(): ?Media
	{
		return $this->media;
	}

	public function setMedia(?Media $media): static
	{
		$this->media = $media;

		return $this;
	}

	public function getParentComment(): ?self
	{
		return $this->parentComment;
	}

	public function setParentComment(?self $parentComment): static
	{
		$this->parentComment = $parentComment;

		return $this;
	}

	/**
	 * @return Collection<int, self>
	 */
	public function getComments(): Collection
	{
		return $this->comments;
	}

	public function getValidComments(): Collection
	{
		return $this->comments->filter(fn(self $comment) => $comment->getStatus() === CommentStatusEnum::VALID);
	}

	public function addComment(self $comment): static
	{
		if (!$this->comments->contains($comment)) {
			$this->comments->add($comment);
			$comment->setParentComment($this);
		}

		return $this;
	}

	public function removeComment(self $comment): static
	{
		if ($this->comments->removeElement($comment)) {
			// set the owning side to null (unless already changed)
			if ($comment->getParentComment() === $this) {
				$comment->setParentComment(null);
			}
		}

		return $this;
	}
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie extends Media
{
}

templates/_partials/pages/movie/cast_card.html.twig
<li class="relative rounded-xl overflow-hidden transition cursor-pointer hover:scale-105 hover:opacity-90 hover:shadow-md">
    <img src="{{ cast.image }}" class="object-cover h-full w-full -z-10" alt="">
    <div class="absolute top-0 h-full w-full bg-gradient-to-t from-black/50 p-3 flex flex-col justify-end">
        <div class="self-center flex flex-col items-center space-y-2">
            <span class="capitalize text-white font-medium drop-shadow-md">{{ cast.name }}</span>
            <span class="text-gray-100 text-xs truncate">Dominic Cobb, {{ cast.role }}</span>
        </div>
    </div>
</li>

templates/_partials/pages/movie/comment.html.twig
<li class="mt-9">
    <div class="bg-gray-100 p-4 rounded-lg">
        <div class="flex items-center">
            <img src="https://random.imagecdn.app/100/100?a" class="w-10 h-10 rounded-full" alt="">
            <div class="ml-4 w-full">
                <span class="font-medium">{{ comment.author.username }}</span>
                <span class="text-xs text-gray-500 flex items-center justify-between w-full">
                    Il y a 2 jours
                </span>
            </div>
        </div>
        <p class="mt-4 w-full">{{ comment.content }}</p>
    </div>
</li>
{% for childComment in comment.validComments %}
    <li class="mt-9 pl-9 border-l-4">
        <div class="bg-gray-100 p-4 rounded-lg">
            <div class="flex items-center">
                <img src="https://random.imagecdn.app/100/100?b" class="w-10 h-10 rounded-full" alt="">
                <div class="ml-4 w-full">
                    <span class="font-medium">{{ childComment.author.username }}</span>
                    <span class="text-xs text-gray-500 flex items-center justify-between w-full">
                        Il y a 4 heures
                    </span>
                </div>
            </div>
            <p class="mt-4 w-full">{{ childComment.content }}</p>
        </div>
    </li>
{% endfor %}
<li class="mt-9 pl-9 border-l-4 relative cursor-not-allowed">
    <span class="absolute top-2 right-2 px-3 py-1 bg-orange-100 rounded-md">En attente de vérification</span>
    <div class="bg-gray-100 p-4 rounded-lg opacity-40">
        <div class="flex items-center">
            <img src="https://random.imagecdn.app/100/100?c" class="w-10 h-10 rounded-full" alt="">
            <div class="ml-4 w-full">
                <span class="font-medium">Harry Potter</span>
                <span class="text-xs text-gray-500 flex items-center justify-between w-full">
                                    <span>Il y a 1O secondes</span>
                                    <span></span>
                                </span>
            </div>
        </div>
        <p class="mt-4 w-full">Lorem ipsum dolor sit amet !!</p>
    </div>
</li>

templates/_partials/pages/movie/staff_card.html.twig
<li class="relative rounded-xl overflow-hidden transition cursor-pointer hover:scale-105 hover:opacity-90 hover:shadow-md">
    <img src="{{ staff.image }}" class="object-cover h-full w-full -z-10" alt="">
    <div class="absolute top-0 h-full w-full bg-gradient-to-t from-black/50 p-3 flex flex-col justify-end">
        <div class="self-center flex flex-col items-center space-y-2">
            <span class="capitalize text-white font-medium drop-shadow-md">{{ staff.name }}</span>
            <span class="text-gray-100 text-xs">{{ staff.role }}</span>
        </div>
    </div>
</li>